src: Add button to code coverage report to get Exclude command.
nickg/nvc pull request #600
Opened 2023-01-27 19:23 UTC by Blebowski

This MR adds a button to the generated Code coverage report which copies
the "exclude" command for respective bins / coverage tag into the clipboard.

Code coverage analysis then can work like so:
1. generate report with empty exclude file passed
2. View the report, get the exclude command, paste it to opened exclude file in IDE / Text editor
3. Regenerate report
4. Go to step 2 again until you have reached 100 % or found something what should not be excluded. In such case, write test which stimulates the situation and gets the code covered.

I have seen this sort of "working model" working for many verification engineers.

I tried to keep the changes simple.

The new button has different CSV style than the buttons for switching tabs. I will tackle that in
next MR where I would like to optimize the size of the generated HTML and also speed of generation.

2023-01-27 19:39 UTC, Blebowski commented
I did not add a test since I don't really know how to test this feature without some sort-of
"clicking framework" and repetitive check on the generated report. It seemed an overkill
for this case. I have of course tried it manually though.

2023-01-27 20:16 UTC, nickg requested changes

2023-01-27 20:16 UTC, nickg commented on src/rt/cover.c
> +   if (flag)
Put braces around the outer if and for statements

2023-01-27 20:16 UTC, nickg commented on src/rt/cover.c
> +         fprintf(f, "<th style=\"width:150px;\">Exclude Command</th>");
Too much indentation

2023-01-27 20:16 UTC, nickg commented on src/rt/cover.c
> +   char t_str[6] = {0};
These two don't actually need to be arrays as you only write constant strings into them: just make them `const char *`.

2023-01-27 20:17 UTC, nickg commented
> I did not add a test since I don't really know how to test this feature without some sort-of "clicking framework" and repetitive check on the generated report. It seemed an overkill for this case. I have of course tried it manually though.

It's fine to test this sort of thing manually.

2023-01-28 14:32 UTC, nickg approved these changes

2023-01-28 14:32 UTC, merged